# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The TCA Podcast
email: TCACastAus@gmail.com
description: "Your weekly dose of antidepressant."
subtitle: "Your weekly dose of antidepressant."
lang: en-us
author: Chris Hughes, Tom Malkin and Kyle Dunlop
copyright: "&#xA9; 2015"
baseurl: "/The-TCA-Podcast" # the subpath of your site, e.g. /blog
# url: "http://linkrot.net" # the base hostname & protocol for your site
url: "https://tcacastaus.github.io"
# twitter_username: timklapdor
# github_username:  timklapdor

permalink: /:year/:title.html

#Timezone
timezone: Australia/Sydney

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']
